version: '3.4'

services:
  app:
    build: ./
    ports:
      - 8082:8082
    container_name: vktestapp2
    restart: unless-stopped
    depends_on:
      - postgre
    environment:
      - DB_PASSWORD=root
      - PASSWORD_SALT=woregjflqwjeiwqjmfljgvnkrjweoiqopoqghewkasdcknvbjnrwekuwiejlqwnb
      - JWTSALT=ijniljew9753nvnalqo3jnbskqo2u57dnveks,cmvjrkwlamckgfk3la,mcmvkrlq;s,cmngjeuqjajdurjfc
  postgre:
    container_name: postgg
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    restart: unless-stopped